
# SEO settings
title: "Zhuanhao "
title2: "Wu" # default: ""
description: "Wu Zhuanhao's site"
keywords: "Wu Zhuanhao, Computer Architecture, Computer Hardware"
url: https://zhuanhao-wu.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
#repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "hnbloggithub"
#twitter_username: "HeiswayiNrird"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Zhuanhao Wu"
  job      : "Graduate Student"
  bio      : ""
  thumb    : /images/author.jpg
  email    : zhuanhao.wu@uwaterloo.ca
  url      : http://zhuanhao-wu.github.io
  github   : http://github.com/zhuanhao-wu
#  twitter  : http://twitter.com/HeiswayiNrird
#  facebook : https://www.facebook.com/heiswayi.nrird
#  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
    #   - slug : blog
    #     title: Blog
    #   - slug : project
    #     title: Projects
    #   - slug : research
    #     title: Research

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
